// <auto-generated />
namespace BitmPosSystem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_purchaseModel_add_organisetion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_purchaseModel_add_organisetion));
        
        string IMigrationMetadata.Id
        {
            get { return "201806061611392_Update_purchaseModel_add_organisetion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
